language: python
python: 
  - '3.8'

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create -f environment.yml
  - source activate mrsensemakr

script:
  - export PATH="$HOME/miniconda/bin":"$HOME/miniconda/envs/mrsensemakr/bin":$PATH
  - make -C docs/ html
  - touch docs/build/html/.nojekyll
deploy:
  - provider: pages
  - strategy: git
    on:
      branch: master
  - verbose: true
  - skip_cleanup: true
  - token: $GITHUB_TOKEN
  - edge: true
  - local_dir: ./docs/build/html/
  - keep_history: true
  - target_branch: master
  - fqdn: www.brianlhill.info
